/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package task1_calculator;

import javax.swing.JOptionPane;

/**
 *
 * @author Dell
 */
public class Calculator extends javax.swing.JFrame {

    /**
     * Creates new form Calculator
     */
    
    
    //Creating Variables for sums
    double Entry1 = 0 ,Entry2 =0 ;
    double  entries;
    double sum =0;
    String SumSign;
    
    public Calculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ResultsTextField = new java.awt.TextField();
        AdditionButton = new javax.swing.JButton();
        OnButton = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();
        EightButton = new javax.swing.JButton();
        NineButton = new javax.swing.JButton();
        SevenButton = new javax.swing.JButton();
        FiveButton = new javax.swing.JButton();
        SixButton = new javax.swing.JButton();
        FourButton = new javax.swing.JButton();
        TwoButton = new javax.swing.JButton();
        ThreeButton = new javax.swing.JButton();
        ZeroButton = new javax.swing.JButton();
        EraseButton = new javax.swing.JButton();
        SubtractButton = new javax.swing.JButton();
        MultiplicationSign = new javax.swing.JButton();
        OffButton = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        EqualButton = new javax.swing.JButton();
        OneButton = new javax.swing.JButton();
        DotButton = new javax.swing.JButton();
        DivisionSign = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(ResultsTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 390, 40));

        AdditionButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        AdditionButton.setText("+");
        AdditionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdditionButtonActionPerformed(evt);
            }
        });
        getContentPane().add(AdditionButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, 80, 40));

        OnButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        OnButton.setText("ON");
        OnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OnButtonActionPerformed(evt);
            }
        });
        getContentPane().add(OnButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 80, 40));

        BackButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BackButton.setText("←");
        BackButton.setToolTipText("");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        getContentPane().add(BackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 80, 40));

        EightButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        EightButton.setText("8");
        EightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EightButtonActionPerformed(evt);
            }
        });
        getContentPane().add(EightButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 80, 40));

        NineButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        NineButton.setText("9");
        NineButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NineButtonActionPerformed(evt);
            }
        });
        getContentPane().add(NineButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 80, 40));

        SevenButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        SevenButton.setText("7");
        SevenButton.setToolTipText("");
        SevenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SevenButtonActionPerformed(evt);
            }
        });
        getContentPane().add(SevenButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 80, 40));

        FiveButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        FiveButton.setText("5");
        FiveButton.setToolTipText("");
        FiveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FiveButtonActionPerformed(evt);
            }
        });
        getContentPane().add(FiveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 80, 40));

        SixButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        SixButton.setText("6");
        SixButton.setToolTipText("");
        SixButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SixButtonActionPerformed(evt);
            }
        });
        getContentPane().add(SixButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 80, 40));

        FourButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        FourButton.setText("4");
        FourButton.setToolTipText("");
        FourButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FourButtonActionPerformed(evt);
            }
        });
        getContentPane().add(FourButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 80, 40));

        TwoButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        TwoButton.setText("2");
        TwoButton.setToolTipText("");
        TwoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TwoButtonActionPerformed(evt);
            }
        });
        getContentPane().add(TwoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 80, 40));

        ThreeButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ThreeButton.setText("3");
        ThreeButton.setToolTipText("");
        ThreeButton.setActionCommand("3");
        ThreeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThreeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ThreeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, 80, 40));

        ZeroButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ZeroButton.setText("0");
        ZeroButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZeroButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ZeroButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 80, 40));

        EraseButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        EraseButton.setText("C");
        EraseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EraseButtonActionPerformed(evt);
            }
        });
        getContentPane().add(EraseButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 80, 40));

        SubtractButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        SubtractButton.setText("-");
        SubtractButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubtractButtonActionPerformed(evt);
            }
        });
        getContentPane().add(SubtractButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 240, 80, 40));

        MultiplicationSign.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        MultiplicationSign.setText("*");
        MultiplicationSign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MultiplicationSignActionPerformed(evt);
            }
        });
        getContentPane().add(MultiplicationSign, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 300, 80, 40));

        OffButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        OffButton.setText("OFF");
        OffButton.setToolTipText("");
        OffButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OffButtonActionPerformed(evt);
            }
        });
        getContentPane().add(OffButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, 80, 40));

        jButton17.setText("jButton1");
        getContentPane().add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, 80, 40));

        EqualButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        EqualButton.setText("=");
        EqualButton.setActionCommand("=");
        EqualButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EqualButtonActionPerformed(evt);
            }
        });
        getContentPane().add(EqualButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, 80, 40));

        OneButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        OneButton.setText("1");
        OneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OneButtonActionPerformed(evt);
            }
        });
        getContentPane().add(OneButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 80, 40));

        DotButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        DotButton.setText(".");
        DotButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DotButtonActionPerformed(evt);
            }
        });
        getContentPane().add(DotButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 80, 40));

        DivisionSign.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        DivisionSign.setText("/");
        DivisionSign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DivisionSignActionPerformed(evt);
            }
        });
        getContentPane().add(DivisionSign, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 360, 80, 40));

        jButton22.setText("jButton1");
        getContentPane().add(jButton22, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 360, 80, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Calculation(String m)
    {
    
        //Creating Calculations
        
        String Results = ResultsTextField.getText() + m;
        ResultsTextField.setText(Results);
    } 
    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
       String Back = null;
       
       if(ResultsTextField.getText().length()>0)
       {
       StringBuilder bac = new StringBuilder(ResultsTextField.getText());
       bac.deleteCharAt(ResultsTextField.getText().length() -1);
       Back =bac.toString();
       ResultsTextField.setText(Back);
       
       }
    }//GEN-LAST:event_BackButtonActionPerformed

    private void OneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OneButtonActionPerformed
        //Storing number
        Calculation("1");
    }//GEN-LAST:event_OneButtonActionPerformed

    private void TwoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TwoButtonActionPerformed
        //Storing number
        Calculation("2");
    }//GEN-LAST:event_TwoButtonActionPerformed

    private void ThreeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThreeButtonActionPerformed
       //Storing number
        Calculation("3");
    }//GEN-LAST:event_ThreeButtonActionPerformed

    private void FourButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FourButtonActionPerformed
        //Storing number
        Calculation("4");
    }//GEN-LAST:event_FourButtonActionPerformed

    private void FiveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FiveButtonActionPerformed
        //Storing number
        Calculation("5");
    }//GEN-LAST:event_FiveButtonActionPerformed

    private void SixButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SixButtonActionPerformed
        //Storing number
        Calculation("6");
    }//GEN-LAST:event_SixButtonActionPerformed

    private void SevenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SevenButtonActionPerformed
        //Storing number
        Calculation("7");
    }//GEN-LAST:event_SevenButtonActionPerformed

    private void EightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EightButtonActionPerformed
        //Storing number
        Calculation("8");
    }//GEN-LAST:event_EightButtonActionPerformed

    private void NineButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NineButtonActionPerformed
        //Storing number
        Calculation("9");
    }//GEN-LAST:event_NineButtonActionPerformed

    private void ZeroButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZeroButtonActionPerformed
        //Storing number
        Calculation("0");
    }//GEN-LAST:event_ZeroButtonActionPerformed

    private void DotButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DotButtonActionPerformed
         //Working on the dot sign
      if(! ResultsTextField.getText().contains("."))
      {
      
          ResultsTextField.setText(ResultsTextField.getText() + DotButton.getText());
      }
    }//GEN-LAST:event_DotButtonActionPerformed

    private void EqualButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EqualButtonActionPerformed
       //Getting Final Product
       
       
       Entry2 = Double.parseDouble(ResultsTextField.getText());
       
       if(SumSign =="+")
       {   
       sum =  Entry1 +Entry2;
       ResultsTextField.setText(String.valueOf(sum));
           
       } else  if(SumSign =="-")
       {
       sum = Entry1 - Entry2;
       ResultsTextField.setText(String.valueOf(sum));
       }else  if(SumSign =="*")
       {
       sum = Entry1 * Entry2;
       ResultsTextField.setText(String.valueOf(sum));
       }else if(SumSign =="/")
       {
       sum = Entry1 / Entry2;
       ResultsTextField.setText(String.valueOf(sum));
       }
       
       
           }//GEN-LAST:event_EqualButtonActionPerformed

    private void DivisionSignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DivisionSignActionPerformed
       //Working on the division sign
       try{
       Entry1 = Double.parseDouble(ResultsTextField.getText());
       ResultsTextField.setText("");
       SumSign = "/";
       }catch(Exception ax)
       {
       ResultsTextField.setText("/");
       }
    }//GEN-LAST:event_DivisionSignActionPerformed

    private void MultiplicationSignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MultiplicationSignActionPerformed
          //Working on the Multiplication sign
          try{
       Entry1 = Double.parseDouble(ResultsTextField.getText());
       ResultsTextField.setText("");
       SumSign = "*";}
          catch(Exception az)
          {
           ResultsTextField.setText("*");
          }
    }//GEN-LAST:event_MultiplicationSignActionPerformed

    private void SubtractButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubtractButtonActionPerformed
         //Working on the Substration sign
         try{
       Entry1 = Double.parseDouble(ResultsTextField.getText());
       ResultsTextField.setText("");
       SumSign = "-";}
          catch(Exception az)
          {
           ResultsTextField.setText("-");
          }
    }//GEN-LAST:event_SubtractButtonActionPerformed

    private void AdditionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdditionButtonActionPerformed
         //Working on the Addition  sign
         try{
       Entry1 = Double.parseDouble(ResultsTextField.getText());
       ResultsTextField.setText("");
       SumSign = "+";}
          catch(Exception az)
          {
           ResultsTextField.setText("+");
          }
    }//GEN-LAST:event_AdditionButtonActionPerformed

    private void OffButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OffButtonActionPerformed
         System.exit(0);
    }//GEN-LAST:event_OffButtonActionPerformed

    private void OnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OnButtonActionPerformed
         //Working on the On Button
         ResultsTextField.setText("");
         
    }//GEN-LAST:event_OnButtonActionPerformed

    private void EraseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EraseButtonActionPerformed
         //Working on Erase Buttons
         ResultsTextField.setText("");
         String Num1 ,Num2;
         
         Num1 = String.valueOf(Entry1);
         Num2 = String.valueOf(Entry2);
         
         Num1 =" ";
         Num2 ="";
    }//GEN-LAST:event_EraseButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdditionButton;
    private javax.swing.JButton BackButton;
    private javax.swing.JButton DivisionSign;
    private javax.swing.JButton DotButton;
    private javax.swing.JButton EightButton;
    private javax.swing.JButton EqualButton;
    private javax.swing.JButton EraseButton;
    private javax.swing.JButton FiveButton;
    private javax.swing.JButton FourButton;
    private javax.swing.JButton MultiplicationSign;
    private javax.swing.JButton NineButton;
    private javax.swing.JButton OffButton;
    private javax.swing.JButton OnButton;
    private javax.swing.JButton OneButton;
    private java.awt.TextField ResultsTextField;
    private javax.swing.JButton SevenButton;
    private javax.swing.JButton SixButton;
    private javax.swing.JButton SubtractButton;
    private javax.swing.JButton ThreeButton;
    private javax.swing.JButton TwoButton;
    private javax.swing.JButton ZeroButton;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton22;
    // End of variables declaration//GEN-END:variables
}
